---
- hosts: frontend-*
  gather_facts: False
  become: true
  pre_tasks:
    - name: Install Python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup:
  roles:
    - autoid-web
